### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by ptsiogas** [Johan-dutoit/JVFloatSharp#2]
Caused by md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.ExecutionEngineException: SIGILL
  at Android.Animation.Animator.add_AnimationEnd (System.EventHandler value) <0x7f8fc2ec50 + 0x00000> in <filename unknown>:0 
  at JVFloatSharp.FloatLabeledEditText.SetShowHint () <0x7f8d362a80 + 0x00513> in <filename unknown>:0 
  at JVFloatSharp.FloatLabeledEditText.EditTextAfterTextChanged (System.Object sender, Android.Text.AfterTextChangedEventArgs e) <0x7f8d3629d0 + 0x00037> in <filename unknown>:0 
  at Android.Text.TextWatcherImplementor.Android.Text.ITextWatcher.AfterTextChanged (IEditable s) <0x7f8d362938 + 0x0005f> in <filename unknown>:0 
  at Android.Text.ITextWatcherInvoker.n_AfterTextChanged_Landroid_text_Editable_ (IntPtr jnienv, IntPtr native__this, IntPtr native_s) <0x7f8d362478 + 0x00077> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:8ad68192-cae6-405b-b4e1-f4c043d9113d (intptr,intptr,intptr)
       at mono.android.text.TextWatcherImplementor.n_afterTextChanged(TextWatcherImplementor.java)
       at mono.android.text.TextWatcherImplementor.afterTextChanged(TextWatcherImplementor.java:32)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9195)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11939)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1047)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:564)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:494)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:34)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:691)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:184)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)

**Comment by Johan-dutoit** [comment]
There is no point using this anymore, you can now use the built in floating labels :)

**Comment by ptsiogas** [comment]
I see, thanks a lot.
